package br.com.kutuar.seguranca.enums;

public enum Permissao {
    ESCOLA_VISUALIZAR,
    ESCOLA_CRIAR,
    ESCOLA_EDITAR,
    ESCOLA_BLOQUEAR,

    USUARIO_VISUALIZAR,
    USUARIO_CRIAR,
    USUARIO_EDITAR,
    USUARIO_BLOQUEAR,
    USUARIO_APROVAR,

    ALUNO_VISUALIZAR,
    ALUNO_CRIAR,
    ALUNO_EDITAR,

    MATRICULA_VISUALIZAR,
    MATRICULA_CRIAR,
    MATRICULA_EDITAR,

    TURMA_VISUALIZAR,
    TURMA_GERENCIAR,

    NOTA_VISUALIZAR,
    NOTA_LANCAR,

    FREQUENCIA_VISUALIZAR,
    FREQUENCIA_LANCAR,

    FINANCEIRO_VISUALIZAR,
    FINANCEIRO_GERENCIAR,

    AUDITORIA_VISUALIZAR
}
