-- Expansão de modelos para o Educacenso

-- 1. Escola
ALTER TABLE escola
    ADD COLUMN IF NOT EXISTS codigo_inep VARCHAR(20),
    ADD COLUMN IF NOT EXISTS situacao_funcionamento VARCHAR(50),
    ADD COLUMN IF NOT EXISTS data_inicio_ano_letivo DATE,
    ADD COLUMN IF NOT EXISTS data_termino_ano_letivo DATE,
    ADD COLUMN IF NOT EXISTS latitude VARCHAR(50),
    ADD COLUMN IF NOT EXISTS longitude VARCHAR(50),
    ADD COLUMN IF NOT EXISTS zona VARCHAR(20),
    ADD COLUMN IF NOT EXISTS localizacao_diferenciada VARCHAR(100),
    ADD COLUMN IF NOT EXISTS dependencia_administrativa VARCHAR(50),
    ADD COLUMN IF NOT EXISTS regulamentacao_numero VARCHAR(100),
    ADD COLUMN IF NOT EXISTS regulamentacao_data DATE,
    ADD COLUMN IF NOT EXISTS infra_agua VARCHAR(100),
    ADD COLUMN IF NOT EXISTS infra_energia VARCHAR(100),
    ADD COLUMN IF NOT EXISTS infra_esgoto VARCHAR(100),
    ADD COLUMN IF NOT EXISTS infra_lixo VARCHAR(100),
    ADD COLUMN IF NOT EXISTS qtd_computadores INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS tem_internet BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS tipo_banda_larga VARCHAR(100),
    ADD COLUMN IF NOT EXISTS lingua_ministrada VARCHAR(50);

-- 2. Turma
ALTER TABLE turma
    ADD COLUMN IF NOT EXISTS tipo_mediador VARCHAR(50),
    ADD COLUMN IF NOT EXISTS horario_inicio TIME,
    ADD COLUMN IF NOT EXISTS horario_termino TIME,
    ADD COLUMN IF NOT EXISTS dias_semana VARCHAR(255),
    ADD COLUMN IF NOT EXISTS carga_horaria INTEGER,
    ADD COLUMN IF NOT EXISTS tipo_atendimento VARCHAR(50),
    ADD COLUMN IF NOT EXISTS modalidade_ensino VARCHAR(50),
    ADD COLUMN IF NOT EXISTS etapa_ensino VARCHAR(100),
    ADD COLUMN IF NOT EXISTS forma_organizacao VARCHAR(50);

-- 3. Aluno
ALTER TABLE aluno
    ADD COLUMN IF NOT EXISTS codigo_inep VARCHAR(20),
    ADD COLUMN IF NOT EXISTS nome_filiacao VARCHAR(255),
    ADD COLUMN IF NOT EXISTS sexo VARCHAR(20),
    ADD COLUMN IF NOT EXISTS cor_raca VARCHAR(50),
    ADD COLUMN IF NOT EXISTS nacionalidade VARCHAR(50),
    ADD COLUMN IF NOT EXISTS uf_nascimento VARCHAR(2),
    ADD COLUMN IF NOT EXISTS municipio_nascimento VARCHAR(100),
    ADD COLUMN IF NOT EXISTS certidao_nascimento VARCHAR(100),
    ADD COLUMN IF NOT EXISTS nis VARCHAR(20),
    ADD COLUMN IF NOT EXISTS cep VARCHAR(20),
    ADD COLUMN IF NOT EXISTS endereco VARCHAR(255),
    ADD COLUMN IF NOT EXISTS numero VARCHAR(20),
    ADD COLUMN IF NOT EXISTS complemento VARCHAR(100),
    ADD COLUMN IF NOT EXISTS bairro VARCHAR(100),
    ADD COLUMN IF NOT EXISTS cidade VARCHAR(100),
    ADD COLUMN IF NOT EXISTS estado VARCHAR(2),
    ADD COLUMN IF NOT EXISTS zona VARCHAR(20),
    ADD COLUMN IF NOT EXISTS localizacao_diferenciada VARCHAR(100),
    ADD COLUMN IF NOT EXISTS usa_transporte_escolar BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS responsavel_transporte VARCHAR(50),
    ADD COLUMN IF NOT EXISTS tipo_acessibilidade VARCHAR(50),
    ADD COLUMN IF NOT EXISTS recursos_acessibilidade TEXT;

-- 4. Professor
ALTER TABLE professor
    ADD COLUMN IF NOT EXISTS sexo VARCHAR(20),
    ADD COLUMN IF NOT EXISTS cor_raca VARCHAR(50),
    ADD COLUMN IF NOT EXISTS nacionalidade VARCHAR(50),
    ADD COLUMN IF NOT EXISTS uf_nascimento VARCHAR(2),
    ADD COLUMN IF NOT EXISTS municipio_nascimento VARCHAR(100),
    ADD COLUMN IF NOT EXISTS cep VARCHAR(20),
    ADD COLUMN IF NOT EXISTS endereco VARCHAR(255),
    ADD COLUMN IF NOT EXISTS numero VARCHAR(20),
    ADD COLUMN IF NOT EXISTS complemento VARCHAR(100),
    ADD COLUMN IF NOT EXISTS bairro VARCHAR(100),
    ADD COLUMN IF NOT EXISTS cidade VARCHAR(100),
    ADD COLUMN IF NOT EXISTS estado VARCHAR(2),
    ADD COLUMN IF NOT EXISTS zona VARCHAR(20),
    ADD COLUMN IF NOT EXISTS escolaridade VARCHAR(50),
    ADD COLUMN IF NOT EXISTS curso_superior_nome VARCHAR(255),
    ADD COLUMN IF NOT EXISTS curso_superior_area VARCHAR(100),
    ADD COLUMN IF NOT EXISTS curso_superior_ano INTEGER,
    ADD COLUMN IF NOT EXISTS curso_superior_instituicao VARCHAR(255),
    ADD COLUMN IF NOT EXISTS pos_graduacao VARCHAR(50),
    ADD COLUMN IF NOT EXISTS funcao_exercida VARCHAR(50),
    ADD COLUMN IF NOT EXISTS tipo_vinculo VARCHAR(50);