-- V22__turma_serie_censo_escolar.sql
-- Campos do Censo Escolar / Educacenso para Turma e Série (Fase 2).

ALTER TABLE turma
    ADD COLUMN IF NOT EXISTS tipo_mediador VARCHAR(20) NOT NULL DEFAULT 'PRESENCIAL', -- PRESENCIAL, EAD, SEMIPRESENCIAL
    ADD COLUMN IF NOT EXISTS hora_inicio TIME,
    ADD COLUMN IF NOT EXISTS hora_termino TIME,
    ADD COLUMN IF NOT EXISTS dias_semana VARCHAR(50), -- ex.: "SEG,TER,QUA,QUI,SEX"
    ADD COLUMN IF NOT EXISTS carga_horaria_semanal INTEGER,
    ADD COLUMN IF NOT EXISTS tipo_atendimento VARCHAR(30) NOT NULL DEFAULT 'ESCOLARIZACAO', -- ESCOLARIZACAO, AEE, ATIVIDADE_COMPLEMENTAR
    ADD COLUMN IF NOT EXISTS modalidade_ensino VARCHAR(30) NOT NULL DEFAULT 'REGULAR', -- REGULAR, EDUCACAO_ESPECIAL, EJA, PROFISSIONAL
    ADD COLUMN IF NOT EXISTS forma_organizacao VARCHAR(30) NOT NULL DEFAULT 'SERIE_ANO'; -- SERIE_ANO, CICLO, PERIODOS_SEMESTRAIS, MODULOS, MULTISSERIADO

-- Etapa de Ensino da Série — lista essencial do Educacenso; pode crescer
-- conforme necessário (ex.: diferenciar 1º-5º e 6º-9º ano do Fundamental).
ALTER TABLE serie
    ADD COLUMN IF NOT EXISTS etapa_ensino VARCHAR(40); -- INFANTIL_CRECHE, INFANTIL_PRE_ESCOLA, FUNDAMENTAL_ANOS_INICIAIS, FUNDAMENTAL_ANOS_FINAIS, MEDIO, EJA, TECNICO